# -*- coding: utf-8 -*-
"""BioInformatika 2 laboras 5 punktas.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/16TCoEgAs2bJuLbgUVQAfLmfggV_0JF8o

**Vainiaus Kriščiūno** BioInformatikos 2 laboratorinio darbo 5 punkto sprendimas

Use ETE3 python package to add root on the camel virus (http://etetoolkit.org/docs/latest/tutorial/index.html). Command “set_outgroup”

Tree:

(KF293666.1:0.00064,KF293664.1:0.00064,(MW039392.1:0.00711,((MT085168.1:0.05963,(MT085175.1:0.0,MT085172.1:0.0):0.02273)1.000:1.01966,((MZ064540.1:0.0,MZ064531.1:0.0):1.55326,(LC469308.1:0.16594,NC_034440.1:0.19411)1.000:0.64656)0.616:0.06218)1.000:1.41024)0.987:0.01494);
"""

pip install ete3

from ete3 import Tree

generated_tree = '(KF293666.1:0.00064,KF293664.1:0.00064,(MW039392.1:0.00711,((MT085168.1:0.05963,(MT085175.1:0.0,MT085172.1:0.0):0.02273)1.000:1.01966,((MZ064540.1:0.0,MZ064531.1:0.0):1.55326,(LC469308.1:0.16594,NC_034440.1:0.19411)1.000:0.64656)0.616:0.06218)1.000:1.41024)0.987:0.01494);'

camel_virus = 'MT085175.1'
# camel_virus = 'MN514967.1'

t1 = Tree(generated_tree, format=1)

print('Prieš:')
print(t1)

print()

t1.set_outgroup(camel_virus)

print('Po:')
print(t1)